/**
 * GitHub Issues notification service.
 * Creates GitHub Issues for new vulnerabilities after scan.
 * Idempotent: one issue per scan (deduped via github_issue_notifications table).
 * Schema: aligned with 002_alter_schema_to_v2 migration.
 */

import { Octokit } from '@octokit/rest'
import { createAdminClient } from '@/lib/supabase/server'

export interface CreateIssueOptions {
  scanId: string
  repositoryId: string
  repoFullName: string    // "owner/repo"
  githubToken: string
  minSeverity?: 'critical' | 'high' | 'medium' | 'low'
}

const SEVERITY_ORDER = ['critical', 'high', 'medium', 'low', 'info'] as const
type Severity = typeof SEVERITY_ORDER[number]

function severityEmoji(s: Severity): string {
  const map: Record<Severity, string> = {
    critical: '🔴',
    high: '🟠',
    medium: '🟡',
    low: '🔵',
    info: '⚪',
  }
  return map[s]
}

function buildIssueBody(
  vulns: Array<{
    osv_id: string
    package_name: string
    package_version: string | null
    version: string | null  // legacy compat
    severity: Severity
    summary: string | null
    fixed_version: string | null
    safe_version: string | null  // legacy compat
    fix_available: boolean | null
    ecosystem: string | null
    osv_url: string | null
  }>,
  repoFullName: string,
  scanId: string,
): string {
  const critical = vulns.filter(v => v.severity === 'critical')
  const high = vulns.filter(v => v.severity === 'high')
  const medium = vulns.filter(v => v.severity === 'medium')
  const low = vulns.filter(v => v.severity === 'low')

  const summaryLine = [
    `**${critical.length}** 🔴 critical`,
    `**${high.length}** 🟠 high`,
    `**${medium.length}** 🟡 medium`,
    `**${low.length}** 🔵 low`,
  ].join(' | ')

  const rows = vulns
    .sort((a, b) => SEVERITY_ORDER.indexOf(a.severity) - SEVERITY_ORDER.indexOf(b.severity))
    .slice(0, 50)
    .map(v => {
      // Use v2 column name, fall back to legacy
      const ver = v.package_version ?? v.version ?? 'unknown'
      const fixedVer = v.fixed_version ?? v.safe_version
      const hasFix = fixedVer || v.fix_available
      const fix = fixedVer ? `Update to \`${fixedVer}\`` : (hasFix ? 'Fix available' : 'No fix available')
      const osvLink = v.osv_url
        ? `[${v.osv_id}](${v.osv_url})`
        : `[${v.osv_id}](https://osv.dev/vulnerability/${v.osv_id})`
      return `| ${severityEmoji(v.severity)} ${v.severity.toUpperCase()} | \`${v.package_name}\` | \`${ver}\` | ${osvLink} | ${fix} |`
    })
    .join('\n')

  return `## 🔒 DepPulse Security Scan Report

**Repository:** \`${repoFullName}\`  
**Scan ID:** \`${scanId}\`  
**Found:** ${summaryLine}

| Severity | Package | Version | CVE/OSV | Fix |
|----------|---------|---------|---------|-----|
${rows}
${vulns.length > 50 ? `\n> ⚠️ Showing top 50 of ${vulns.length} vulnerabilities.` : ''}

---
*Generated by [DepPulse](https://github.com/sutsko89/deppulse-mvp) • ${new Date().toUTCString()}*
`
}

/**
 * Create a GitHub Issue for a completed scan.
 * Idempotent — checks github_issue_notifications before creating.
 */
export async function createScanIssue(options: CreateIssueOptions): Promise<string | null> {
  const supabase = await createAdminClient()
  const minSeverity = options.minSeverity ?? 'high'
  const [owner, repo] = options.repoFullName.split('/')

  // Idempotency check
  const { data: existing } = await supabase
    .from('github_issue_notifications')
    .select('id, github_issue_url, status')
    .eq('scan_id', options.scanId)
    .eq('status', 'created')
    .maybeSingle()

  if (existing?.github_issue_url) {
    return existing.github_issue_url
  }

  // Create notification record (pending)
  const { data: notif, error: notifError } = await supabase
    .from('github_issue_notifications')
    .insert({
      scan_id: options.scanId,
      repo_id: options.repositoryId,
      severity_filter: minSeverity,
      status: 'pending',
    })
    .select('id')
    .single()

  if (notifError || !notif) {
    throw new Error(`Failed to create notification record: ${notifError?.message}`)
  }

  // Fetch vulnerabilities — select both v2 and legacy column names
  const minIdx = SEVERITY_ORDER.indexOf(minSeverity)
  const severities = SEVERITY_ORDER.slice(0, minIdx + 1)

  const { data: vulns, error: vulnError } = await supabase
    .from('vulnerabilities')
    .select('osv_id, package_name, package_version, version, severity, summary, fixed_version, safe_version, fix_available, ecosystem, osv_url')
    .eq('scan_id', options.scanId)
    .in('severity', severities)
    .order('severity', { ascending: true })

  if (vulnError) throw new Error(`Failed to fetch vulns: ${vulnError.message}`)

  if (!vulns || vulns.length === 0) {
    await supabase.from('github_issue_notifications').update({
      status: 'skipped',
      error_message: 'No vulnerabilities above threshold',
    }).eq('id', notif.id)
    return null
  }

  try {
    const octokit = new Octokit({ auth: options.githubToken })

    const criticalCount = vulns.filter(v => v.severity === 'critical').length
    const issueTitle = criticalCount > 0
      ? `🔴 [DepPulse] ${criticalCount} critical vulnerabilities detected`
      : `🟠 [DepPulse] ${vulns.length} vulnerabilities detected`

    const { data: issue } = await octokit.issues.create({
      owner,
      repo,
      title: issueTitle,
      body: buildIssueBody(
        vulns as Parameters<typeof buildIssueBody>[0],
        options.repoFullName,
        options.scanId,
      ),
      labels: ['security', 'dependencies'],
    })

    await supabase.from('github_issue_notifications').update({
      status: 'created',
      github_issue_number: issue.number,
      github_issue_url: issue.html_url,
      github_issue_title: issue.title,
      is_open: true,
    }).eq('id', notif.id)

    console.log(`[issues] Created GitHub Issue #${issue.number}: ${issue.html_url}`)
    return issue.html_url

  } catch (err) {
    const message = err instanceof Error ? err.message : String(err)
    await supabase.from('github_issue_notifications').update({
      status: 'failed',
      error_message: message,
    }).eq('id', notif.id)
    throw err
  }
}
